# Generated by Django 3.2.7 on 2023-02-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='都道府県',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='都道府県'),
        ),
    ]
