# Generated by Django 3.2.7 on 2023-02-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary_都道府県'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='お名前',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='お名前'),
        ),
        migrations.AddField(
            model_name='diary',
            name='アレルギー',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='アレルギー'),
        ),
        migrations.AddField(
            model_name='diary',
            name='カナ',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='フリガナ'),
        ),
        migrations.AddField(
            model_name='diary',
            name='体温_分',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='体温(分)'),
        ),
        migrations.AddField(
            model_name='diary',
            name='体温_度',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='体温(度)'),
        ),
        migrations.AddField(
            model_name='diary',
            name='具合が悪くなった予防接種名',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='具合が悪くなった予防接種名'),
        ),
        migrations.AddField(
            model_name='diary',
            name='具合悪い点',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='具合悪い点'),
        ),
        migrations.AddField(
            model_name='diary',
            name='前回のワクチンの種類',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='前回のワクチンの種類'),
        ),
        migrations.AddField(
            model_name='diary',
            name='前回の摂取年',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='前回の摂取年'),
        ),
        migrations.AddField(
            model_name='diary',
            name='前回の摂取日',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='前回の摂取日'),
        ),
        migrations.AddField(
            model_name='diary',
            name='前回の摂取月',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='前回の摂取月'),
        ),
        migrations.AddField(
            model_name='diary',
            name='前回受けた予防接種名',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='前回受けた予防接種名'),
        ),
        migrations.AddField(
            model_name='diary',
            name='前回受けた予防接種日',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='前回受けた予防接種日'),
        ),
        migrations.AddField(
            model_name='diary',
            name='加入者番号',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='加入者番号'),
        ),
        migrations.AddField(
            model_name='diary',
            name='市内局番',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='市内局番'),
        ),
        migrations.AddField(
            model_name='diary',
            name='市外局番',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='市外局番'),
        ),
        migrations.AddField(
            model_name='diary',
            name='市町村',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='市町村'),
        ),
        migrations.AddField(
            model_name='diary',
            name='市町村以下の住所',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='市町村以下の住所'),
        ),
        migrations.AddField(
            model_name='diary',
            name='年齢',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='diary',
            name='接種回数',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='接種回数'),
        ),
        migrations.AddField(
            model_name='diary',
            name='病名',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='病名'),
        ),
        migrations.AddField(
            model_name='diary',
            name='症状',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='症状'),
        ),
        migrations.AddField(
            model_name='diary',
            name='誕生日',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='誕生日'),
        ),
    ]
