# Generated by Django 3.2.7 on 2023-02-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20230206_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='タイトル'),
        ),
    ]
