# Generated by Django 3.2.7 on 2023-02-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_diary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
