# Generated by Django 3.2.7 on 2023-02-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_diary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='都道府県の区分',
            field=models.CharField(max_length=10, null=True, verbose_name='都道府県の区分'),
        ),
    ]
