# Generated by Django 3.2.7 on 2023-02-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_diary_都道府県の区分'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='_2週間以内に予防接種を打ちましたか',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='2週間以内に予防接種を打ちましたか？'),
        ),
        migrations.AddField(
            model_name='diary',
            name='_2週間以内に打った予防接種の日付',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='2週間以内に打った予防接種の日付を記入してください'),
        ),
        migrations.AddField(
            model_name='diary',
            name='_2週間以内に打った予防接種の種類',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='2週間以内に打った予防接種の種類を記入してください'),
        ),
        migrations.AddField(
            model_name='diary',
            name='_今日の予防接種について何か質問はありますか',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='今日の予防接種について何か質問はありますか？'),
        ),
        migrations.AddField(
            model_name='diary',
            name='その他に処方されている薬',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='その他に処方されているお薬はありますか？'),
        ),
        migrations.AddField(
            model_name='diary',
            name='その他に処方されている薬名を記入してください',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='その他に処方されている薬名を記入してください'),
        ),
        migrations.AddField(
            model_name='diary',
            name='その他の病気',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='その他の病気'),
        ),
        migrations.AddField(
            model_name='diary',
            name='サラサラにする薬',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='血液をサラサラにする薬を処方されていますか？'),
        ),
        migrations.AddField(
            model_name='diary',
            name='ワクチンの副反応について理解していますか',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ワクチンの副反応について理解していますか？'),
        ),
        migrations.AddField(
            model_name='diary',
            name='ワクチン接種を以前接種したことはありますか',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='前回受けた予防接種日'),
        ),
        migrations.AddField(
            model_name='diary',
            name='上記以外の持病をもっていますか',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='上記以外の持病をもっていますか？'),
        ),
        migrations.AddField(
            model_name='diary',
            name='予防接種で具合が悪くなったことはありますか',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='予防接種で具合が悪くなったことはありますか？'),
        ),
        migrations.AddField(
            model_name='diary',
            name='体に具合悪いところはありますか',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='体に具合悪いところはありますか？'),
        ),
        migrations.AddField(
            model_name='diary',
            name='何らかの投薬を受けていますか',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='何らかの投薬を受けていますか？'),
        ),
        migrations.AddField(
            model_name='diary',
            name='処方されている薬名を記入してください',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='処方されている薬名を記入してください'),
        ),
        migrations.AddField(
            model_name='diary',
            name='持病はありますか',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='持病はありますか？'),
        ),
        migrations.AddField(
            model_name='diary',
            name='接種を希望しますか',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='医師の説明を受け、接種を希望しますか？'),
        ),
        migrations.AddField(
            model_name='diary',
            name='現住所と住民票の住所は同じですか',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='現住所と住民票の住所は同じですか？'),
        ),
        migrations.AddField(
            model_name='diary',
            name='現在妊娠していますか',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='現在妊娠していますか？'),
        ),
        migrations.AddField(
            model_name='diary',
            name='現在治療を受けていますか',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ワクチンの副反応について理解していますか？'),
        ),
        migrations.AddField(
            model_name='diary',
            name='病名を選択してください',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='病名を選択してください'),
        ),
        migrations.AddField(
            model_name='diary',
            name='痙攣を起こしたことはありますか',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='痙攣を起こしたことはありますか？'),
        ),
        migrations.AddField(
            model_name='diary',
            name='重度のアレルギーはありますか',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='重度のアレルギーはありますか？'),
        ),
    ]
